### ISSUE TITLE
Full Image URLs

### ISSUE THREAD

**Issue by acharlop** [celiao/tmdbsimple#11]
Is there a method to create the full url for an image that I'm not seeing? 

I don't mind creating a pull request if not. Just wanted to double check I'm not missing anything.

### [documentation](http://docs.themoviedb.apiary.io/#reference/configuration/configuration)
 To build an image URL, you will need 3 pieces of data. The **base_url**, **size** and **file_path**. Simply
  combine them all and you will have a fully qualified URL. Here’s an example URL:
 `http://image.tmdb.org/t/p/w500/8uO0gUM8aNqYLs1OsTBQiXu0fEv.jpg`

**Comment by celiao** [comment]
To create the full URL for an image, first you would need to get the Configuration info, then access the relevant configuration attributes.

You might want to write your own method for pulling together the relevant attributes for an image URL.  The wrapper features a one-to-one mapping between `tmdbsimple` functions and TMDb methods. It might be difficult to make the method generic enough and to fit it in the structure of the code.
