### ISSUE TITLE
Have there been any changes with the API?

### ISSUE THREAD

**Issue by eiphes** [celiao/tmdbsimple#12]
I've been using using the wrapper for a little bit, but it is no longer working for me.

```
import tmdbsimple as tmdb
tmdb.API_KEY = 'MY-API-KEY'


movie = tmdb.Movies(22021)

title = movie.title

print(title)
```
is returning this error now... 

```
Traceback (most recent call last):
  File "C:/file/...", line 21, in <module>
    title = movie.title
AttributeError: 'Movies' object has no attribute 'title' 
```

This could be very well be on my end: Only thing I did differently this time was pip install tmdbsimple into a new Python3 conda env. However, scripts I've written on Python 2.7 in a different env are now failing also.

I'm sure this issue is on my end, but I thought I'd check with you just in case to see if it's still working fine for you. Thanks!

**Comment by eiphes** [comment]
Sorry, sorry. My fault. While I haven't been able to get TMDBsimple to cooperate on my Python3.5 env, I was completely mistaken about what was causing my issue in the 2.7 script. 

Thank you all the same. Apologies.

**Comment by celiao** [comment]
No worries!
