### ISSUE TITLE
Help getting list of actors and images

### ISSUE THREAD

**Issue by luzer** [celiao/tmdbsimple#13]
hi
love the code, but having trouble getting a list of people from a tv series. any assist, please?
```
import tmdbsimple as tmdb

tmdb.API_KEY = 'x'

tv_show = tmdb.TV(1400) #seinfeld
for person in tv_show.credits():
    #print person
    p = tmdb.People(person)
```

**Comment by amrnablus** [comment]
I need that too, @celiao I can do it myself with some guidance if you'd like

**Comment by luzer** [comment]
i ended up using an alternative package, IMDB Web API, in the end @imdbpie

**Comment by amrnablus** [comment]
I actually managed to get it to work with the movie API, I'll try to run your code and see what might be the issue

**Comment by celiao** [comment]
Hi @luzer and @amrnablus.  The example below should help.

```python
import tmdbsimple as tmdb
tmdb.API_KEY = 'YOUR API KEY HERE'
```

# TV Show Example


```python
tv_show = tmdb.TV(1400)    # Seinfield
```

### The `credits()` method returns three keys


```python
for key in tv_show.credits():
    print(key)
```

    id
    crew
    cast


### We are interested in the cast


```python
for person in tv_show.credits()['cast']:
    print('{} - {} - {}'.format(person['order'], person['id'], person['name']))
```

    0 - 16377 - Jerry Seinfeld
    1 - 1206 - Jason Alexander
    2 - 50807 - Michael Richards
    3 - 15886 - Julia Louis-Dreyfus
    4 - 1211997 - Liz Sheridan
    5 - 4201 - Wayne Knight
    6 - 1212034 - Barney Martin
    7 - 61964 - Estelle Harris
    8 - 62551 - Heidi Swedberg
    9 - 16376 - Larry David
    10 - 44115 - Spike Feresten
    11 - 1223836 - Ruth Cohen
    12 - 26042 - Jerry Stiller


### To get detailed information about one of the cast members, use Person() and info()


```python
person = tmdb.People(16377).info()
for key in person:
    print('{} - {}\n'.format(key, person[key]))
```

    homepage - 
    
    profile_path - /91vcBaUWtFAW0Atrwd384mwRo3A.jpg
    
    biography - From Wikipedia, the free encyclopedia.
    
    Jerome "Jerry" Seinfeld (born April 29, 1954 in Brooklyn, New York, U.S.) is an American stand-up comedian, actor, writer, and television and film producer, known for playing a semi-fictional version of himself in the situation comedy Seinfeld (1989–1998), which he co-created and co-wrote with Larry David, and, in the show's final two seasons, co-executive-produced.
    
    In his first major foray back into the media since the finale of Seinfeld, he co-wrote and co-produced the film Bee Movie, also taking on the lead role of Barry B. Benson. In February 2010, Seinfeld premiered a reality TV series called The Marriage Ref on NBC. Seinfeld was more recently directing Colin Quinn in the Broadway show Long Story Short at the Helen Hayes Theater in New York which ran until January 8, 2011.
    
    Description above from the Wikipedia article Jerry Seinfeld, licensed under CC-BY-SA, full list of contributors on Wikipedia.
    
    birthday - 1954-04-29
    
    also_known_as - []
    
    name - Jerry Seinfeld
    
    place_of_birth - Brooklyn, New York, USA
    
    adult - False
    
    id - 16377
    
    popularity - 2.544699
    
    deathday - 
    
    gender - 0
    
    imdb_id - nm0000632
    


### To get that person's images, use images()


```python
images = tmdb.People(16377).images()
for image in images['profiles']:
    print(image)
    print('\n')
```

    {'iso_639_1': None, 'aspect_ratio': 0.666666666666667, 'height': 720, 'vote_count': 1, 'vote_average': 5.3125, 'file_path': '/91vcBaUWtFAW0Atrwd384mwRo3A.jpg', 'width': 480}
    
    
    {'iso_639_1': None, 'aspect_ratio': 0.666666666666667, 'height': 3000, 'vote_count': 2, 'vote_average': 5.24542124542125, 'file_path': '/cAsXoVf0UmotNUjMggHMnmAj8w.jpg', 'width': 2000}
    
    
    {'iso_639_1': None, 'aspect_ratio': 0.667, 'height': 1000, 'vote_count': 0, 'vote_average': 0.0, 'file_path': '/mDKHFdmfYymOTXxGbVY4nhWTH25.jpg', 'width': 667}
    
    


### You can access the first image with `http://image.tmdb.org/t/p/w500/91vcBaUWtFAW0Atrwd384mwRo3A.jpg` (see Configuration for the available image sizes)
![Jerry Seinfield](http://image.tmdb.org/t/p/w154/91vcBaUWtFAW0Atrwd384mwRo3A.jpg)

**Comment by luzer** [comment]
amazing thank you!
