### ISSUE TITLE
using curl multi

### ISSUE THREAD

**Issue by amrnablus** [celiao/tmdbsimple#14]
Hello,
I'm running into this scenario: I call the discover API, it send back a bunch of incomplete information (to my requirements), which then leads me to calling the movie info API by looping through each movie and calling the info API for each movie --needless to say you can't multi-thread this--
Using the curl multi interface (https://curl.haxx.se/libcurl/c/libcurl-multi.html) Will allow these multiple requests to be handled using curl, and thus faster response.
If you're up for it i can add it.

**Comment by celiao** [comment]
Hi @amrnablus.  Neat concept, but I'd rather not make `tmdbsimple` dependent on another package.  The idea is to keep it _simple_!   Feel free to post an example for interested users.
