### ISSUE TITLE
Discover().Movie() vote_count.gte argument

### ISSUE THREAD

**Issue by brian-regan** [celiao/tmdbsimple#18]
When using the tmdb.Disocver( ).Movie( ) function ([link](https://github.com/celiao/tmdbsimple/blob/master/tmdbsimple/discover.py)) with arguments like sort_by it works fine but the arguments such as vote_count.gte, which include a period raise the error ` keyword can't be an expression`

**Comment by Oli4** [comment]
I have the same problem. I think it is because those are the original arguments from the API but python does not allow for periods in keywords. Maybe you need a mapping from the wrapper argument vote_count_gte to the API argument vote_count.gte

**Comment by celiao** [comment]
Many thanks for your contributions @Oli4 @brian-regan .  I updated the code to allow both underscore (PR #19) and dots (with `kwargs`).  I added a unittest to [tests/test_discover.py](https://github.com/celiao/tmdbsimple/blob/master/tests/test_discover.py) to confirm that both usages work.
