### ISSUE TITLE
Get all of the TV-series

### ISSUE THREAD

**Issue by savandriy** [celiao/tmdbsimple#20]
Is it possible to get all of the TV-series in the database as a list? I mean names of the shows and some basic info.

**Comment by burakozdemir32** [comment]
Of course it's not possible by calling one method of this package. But you can get all of the TV series's informations in a for loop.
For instance;

serie = tmdbsimple.TV()
latest_tv_serie_id = serie.latest()

for serie_id in range(latest_tv_serie_id + 1):
    do_your_magic
