### ISSUE TITLE
Search for all currently showing films in python.

### ISSUE THREAD

**Issue by CarlosPurchase-Galarza** [celiao/tmdbsimple#22]
Hi!

I'm trying to get a list of all of the currently showing films in cinemas. I am usig Python 2.7 and have started playing around with the wrapper tmdbsimple. I'm struggling, does anyone know how to do it? I saw that "api.movie_now_playing()" was a solution but I cannot get it to work. Any ideas? Thanks

Sorry if this is posted in the wrong place.

**Comment by celiao** [comment]
You want the `now_showing` method.

```python
import tmdbsimple as tmdb
tmdb.API_KEY = 'YOUR-API-KEY-HERE'
```

# Now Showing Example
This code displays the first page of movies that are Now Showing.
Uncomment 'response' to view the details.

```python
movies = tmdb.Movies()
response = movies.now_playing(region='US', page=1)
#response
for m in movies.results:
    print m['title']
```

    Logan
    Fifty Shades Darker
    Rings
    Kong: Skull Island
    John Wick: Chapter 2
    Get Out
    xXx: Return of Xander Cage
    The Lego Batman Movie
    The Great Wall
    A Cure for Wellness
    The Space Between Us
    Raw
    The Girl with All the Gifts
    Kidnap
    Before I Fall
    The Shack
    Devil in the Dark
    Fist Fight
    Personal Shopper
    Collide

**Comment by celiao** [comment]
A good place to look for examples is in the `tests/` directory.

**Comment by CarlosPurchase-Galarza** [comment]
Sorry for the late reply, I was working on another part of the project.
Thanks for the code, it works. The only problem is that it is showing some
films that are not currently showing. For example, if I get the first page
of "now playing" in US, "Power Rangers" will appear even though it does not
show until the 24th of March. Do you have any idea of how to only show
films that are actually out and showing on cinemas?

Thanks,
Carlos
