### ISSUE TITLE
"GET" functions overwrite themselves when attribute in response has same name

### ISSUE THREAD

**Issue by aulemahal** [celiao/tmdbsimple#30]
This is concerning the `movies.Movies` object.
When the `keywords()` *method* is called, it overwrites itself by creating the `keywords` *attribute*. Thus making any further call to `keywords()` raise a `TypeError: 'list' object is not callable`.

In the API's docs ([here](https://developers.themoviedb.org/3/movies/get-movie-keywords)) there is not additionnal query parameter listed (other than the `api_key`). Therefore, the only potential argument is `append_to_response`.
This said, one easy solution could be simply transforming the method to a property (with `@property`), but this would eliminate the possibility of using `append_to_response`. I don't have other suggestions for now...

**Comment by aulemahal** [comment]
I just realized that `append_to_response` is not even possible for the `keyword` GET request. Then, my suggestion of turning it into a property should be the easiest, with no loss of functionality.

**Comment by aulemahal** [comment]
Just realized that this is not unique to keywords but to all functions that perform a GET request and get a response which has an attribute of the same name.
Will be submitting a pull request where those attributes are simply not set.

**Comment by celiao** [comment]
Nice find.  Closed by #32.
