### ISSUE TITLE
Boolean arguments don't work.

### ISSUE THREAD

**Issue by Hyperz** [celiao/tmdbsimple#35]
So query variables that expect a boolean value are case-sensitive. They only accept `true` or `false`. However the default string representation of a bool in Python is `'True'` and `'False'`. Because of this passing a bool argument won't do anything as the API will fallback to whatever the default is.

This example will not return any results because `include_adult` will fallback to its default of `false`:
`tmdb.Search().movie(query='She\'s so small', include_adult=True)`

Passing a string does work:
`tmdb.Search().movie(query='She\'s so small', include_adult='true')`

Kind of messy to work around that with if-else statements or `str(expression).lower()`.

**Comment by celiao** [comment]
How are you suggesting the code be changed?

**Comment by Hyperz** [comment]
I'm not super familiar with Python (or tmdbsimple for that matter). Would it make sense to iterate over `params` and copy them into a new dict [here](https://github.com/celiao/tmdbsimple/blob/57770911c88da3b15933bd64b5b953247cf6b50b/tmdbsimple/base.py#L66), with bools converted to lower-case strings?
