### ISSUE TITLE
Documentation improvement: how to close connection

### ISSUE THREAD

**Issue by staticdev** [celiao/tmdbsimple#40]
On mutiple calls I get:
../usr/lib/python3.5/socket.py:646: ResourceWarning: unclosed <socket.socket fd=4, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('150.164.200.104', 51940), raddr=('54.243.67.237', 443)>
  self._sock = None

Nothing in the documentation regards best practices for usage or maybe an example code of how to avoid that. Any thoughts on that?

**Comment by celiao** [comment]
Are you receiving this message only while running the unit tests?

**Comment by staticdev** [comment]
Not only running unit test. I will make some evidence code later today.. my code is just too big yet.

**Comment by staticdev** [comment]
Nevermind, it is not occuring in the latest version 1.8.0. Thanks.
