### ISSUE TITLE
need more detail documentations.

### ISSUE THREAD

**Issue by tigers2020** [celiao/tmdbsimple#43]
would you provide more detail in documents with more examples? like how to use  popular movies or pagination etcs.

**Comment by tigers2020** [comment]
which way calling Movie is better?
movie = tmdb.Movie(342)
info = movie.info()
video = movie.video()
images = movie.images()
or 
info = tmdb.movie(342).info()
video =tmdb.movie(342).video()
image = tmdb.movie(342).images()

**Comment by celiao** [comment]
A good place to find more documentation and examples is the [Closed Issues](https://github.com/celiao/tmdbsimple/issues?q=is%3Aissue+is%3Aclosed).

**Comment by celiao** [comment]
You can call Movies() either way.  It's a matter of preference.

# Movie Examples

```python
import tmdbsimple as tmdb
tmdb.API_KEY = 'YOUR_API_KEY_HERE'
```

## Call Format 1 - Instance attributes
Create an instance of the type Movies.  Call methods on the instance (movie.info(), movie.videos(), and movie.images()).  Then you can access the instance attributes (movie.title, movie.results, movie.posters[0]).  See The Movie Database API for the names of the attributes. For example, https://developers.themoviedb.org/3/movies/get-movie-details for info() attributes.


```python
movie = tmdb.Movies(342)
```


```python
info = movie.info()
videos = movie.videos()
images = movie.images()
```


```python
movie.title, movie.results, movie.posters[0]
```




    ('Summer Storm',
     [{'id': '5581bf5c92514132b800001b',
       'iso_3166_1': 'US',
       'iso_639_1': 'en',
       'key': 'A4YghiZxHfw',
       'name': 'Trailer 1',
       'site': 'YouTube',
       'size': 360,
       'type': 'Trailer'}],
     {'aspect_ratio': 0.6790123456790124,
      'file_path': '/o9J7BEdsv0fUl89WwUCCW9Iq9Xj.jpg',
      'height': 4860,
      'iso_639_1': 'en',
      'vote_average': 5.377289377289378,
      'vote_count': 2,
      'width': 3300})



## Call Format 2 - Direct Access
If you don't create an instance, you need to access the dict values directly.


```python
info = tmdb.Movies(342).info()
videos = tmdb.Movies(342).videos()
images = tmdb.Movies(342).images()
```


```python
info['title'], videos['results'], images['posters'][0]
```




    ('Summer Storm',
     [{'id': '5581bf5c92514132b800001b',
       'iso_3166_1': 'US',
       'iso_639_1': 'en',
       'key': 'A4YghiZxHfw',
       'name': 'Trailer 1',
       'site': 'YouTube',
       'size': 360,
       'type': 'Trailer'}],
     {'aspect_ratio': 0.6790123456790124,
      'file_path': '/o9J7BEdsv0fUl89WwUCCW9Iq9Xj.jpg',
      'height': 4860,
      'iso_639_1': 'en',
      'vote_average': 5.377289377289378,
      'vote_count': 2,
      'width': 3300})

**Comment by tigers2020** [comment]
so calling two option have no different performance?
like option 1 take 0.3 s and option 2 take 0.25 something like that?

**Comment by celiao** [comment]
For this kind of programming, it's more important to care about readability than execution speed.
