### ISSUE TITLE
No ability to search for TV shows based on genre

### ISSUE THREAD

**Issue by Nathan-Nesbitt** [celiao/tmdbsimple#58]
Seems there is the ability to search for Movies of a certain genre using the tmdb.Genres.movies() function, but there is no option to search for TV shows based on a genre. (Unless the movie function also returns TV shows, which would be a different issue).

**Comment by celiao** [comment]
@Nathan-Nesbitt I don't see TMDB endpoints to search Movies or TVs of a particular genre.

From https://developers.themoviedb.org/3/genres/get-movie-list:

![image](https://user-images.githubusercontent.com/5824630/56869993-5f4b0c00-69bd-11e9-98ae-bbe723a9b57e.png)

Perhaps tmdb.Genres.movies() accesses a hidden endpoint or is no longer available.

**Comment by Nathan-Nesbitt** [comment]
Strange, yeah it doesn't seem to be documented but the function still seems to work.

**Comment by AtomicNess123** [comment]
How to get the list of all genres? Thanks.
