### ISSUE TITLE
Question about Videos

### ISSUE THREAD

**Issue by gojonesy** [celiao/tmdbsimple#6]
This is a great utility! Thanks for putting it together.

I am pulling movie objects like so:
```python
movie = tmdb.Movies('tt1074638').info()
```

When I traverse the dictionary, I have noticed that most movies that I return list "False" for the "video" value.
```python
print("Video: ", movie.get('video'))
Video:  False
```

Is there another way to return the video elements? To be sure, I looked at **Skyfall** on TMDB and noticed that it has a trailer associated with it on the site. 

Thanks

**Comment by celiao** [comment]
You can use the `append_to_response` parameter and `trailers` attribute.
```
>>> kwargs = {'append_to_response': 'trailers'}
>>> movie = tmdb.Movies('tt1074638').info(**kwargs)
>>> print("Video: ", movie.get('trailers'))
Video:  {'youtube': [{'source': '6kw1UVovByw', 'type': 'Trailer', 'size': 'HD', 'name': 'Official Trailer'}], 'quicktime': []}
```

Thanks for asking!

**Comment by albertoivo** [comment]
Hello.. How can I get only the `source` attribute in this example above?
