### ISSUE TITLE
V4 api

### ISSUE THREAD

**Issue by Greenhousecafe** [celiao/tmdbsimple#63]
Hi, 
Was wondering if there was any plans to update this for use with the version 4 tmdb api? 
Thanks.

**Comment by staticdev** [comment]
@celiao Do you intent do keep up with this repository? Looking for maintainers?

**Comment by Archmonger** [comment]
TMDB has abandoned all work in the v4 API namespace. To my knowledge, if a future endpoint is released it will be within a v5 namespace.

@celiao This issue can be closed.

**Comment by celiao** [comment]
Thanks for the news, @Archmonger!
