### ISSUE TITLE
Question About Movie Rating

### ISSUE THREAD

**Issue by BagelTime** [celiao/tmdbsimple#7]
I really like this package.  One thing I can't figure out is how to get the movie rating (G, PG etc.)  Can you point me toward the correct function?

For that matter is there an API doc for this package that list all functions and variables?

**Comment by celiao** [comment]
Thanks for letting me know you like this package.  I had fun developing it.  Feel free to give it a *Star*.

The method you want is `releases()`.  Countries have different rating systems, so `releases()` will return release data for each country, including:
- The ISO 3166 country code
- The certification (or movie rating)
- The release date
- A primary release flag

Here's an example of how to extract the certification (or movie rating) information for each country:
```
>>> import tmdbsimple as tmdb
>>> tmdb.API_KEY = 'YOUR_API_KEY_HERE'
>>> movie = tmdb.Movies(603)
>>> response = movie.releases()
>>> for country in movie.countries:
...      print(country['iso_3166_1'] + ': ' + country['certification'])
...
US: R
CZ: 12
NO: A
GB: 15
IT: T
DE: 16
FI: K-16
BR: 12 anos
HU: 12
NL: 12
JP: PG-12
CA: 14A
AQ:
FR: U
BG: C
KR: 12세 관람가
AU: M
```

Check out The Movie Database [documentation](http://docs.themoviedb.apiary.io) for more information about the endpoints, which correspond to the methods in `tmdbsimple`.  For example, go to the `REFERENCE` section of the menu on the left side.  Click on `Movies`, then click on `/movie/{id}/releases`, then click on `GET`.   From the `Response` on the right, you can determine how to extract the information of interest.
