### ISSUE TITLE
 How to change the language of the data it returns to me

### ISSUE THREAD

**Issue by RecoveryyTV** [celiao/tmdbsimple#72]
Hello, I am using the api but I would like it to return the data in Spanish? How or where can I change it to return the descriptions and more information in Spanish?

**Comment by SaltySpaghetti** [comment]
Simply add to your request the language you want

`response: list = search.tv(query="A nice TV show", language="es")["results"]`

**Comment by Archmonger** [comment]
This PR is a question, not a bug report. Can be closed @celiao

**Comment by celiao** [comment]
Thanks, @Archmonger!
