### ISSUE TITLE
Can't find "Watch" endpoint

### ISSUE THREAD

**Issue by SaltySpaghetti** [celiao/tmdbsimple#76]
Hi, I'm try to use this endpoint https://developers.themoviedb.org/3/tv/get-tv-watch-providers but I can't find it in the library. I tried to dig into the library in the TV file, but there's no mark of this method. Is that a new one and is not implemented yet, or I'm missing it? Thank you

**Comment by vinay-krishna9** [comment]
It was not yet introduced till 20 November, 2020.
But the TMDb has partnered with JustWatch to get the list of watch provider availabilities per country by provider.
 
I would like to work on this.

**Comment by vinay-krishna9** [comment]
> It was not yet introduced till 20 November, 2020.
> But the TMDb has partnered with JustWatch to get the list of watch provider availabilities per country by provider.
> 
> I would like to work on this.

vinay-krishna9:providers

**Comment by vinay-krishna9** [comment]
[added watch providers for TV and Movies with unit test cases](#79)

**Comment by vinay-krishna9** [comment]
[added watch providers for TV and Movies with unit test cases #79 ](#79)

**Comment by vinay-krishna9** [comment]
Hi @SaltySpaghetti,

added watch providers for TV and Movies with unit test cases #79 
I have created a pull request witch can close this issue.

**Comment by SaltySpaghetti** [comment]
Thank you so much!

**Comment by celiao** [comment]
Thanks for bring this to our attention, @SaltySpaghetti!

Closed by #79
