### ISSUE TITLE
HTTP requests concurrency problems v2.7.0

### ISSUE THREAD

**Issue by Archmonger** [celiao/tmdbsimple#77]
`urllib3` by default limits concurrent requests to 10.

So for tmdbsiple, if you have multiple threads executing, you'll get `WARNING urllib3.connectionpool: Connection pool is full, discarding connection`.

I'd assume that it's related to the new global `REQUESTS_SESSION`, as this wasn't an issue on v2.6.0.

**Comment by p0psicles** [comment]
tmdbsimple was already using a session from requests.
The change now only made it possible to `optionally` provide your own session object

**Comment by Archmonger** [comment]
Just looked over the code for base.py, you're right. I'll look over a diff between 2.6.0 and 2.7.0 to trace down why those urlib3 warnings don't occur on 2.6.0 for me.

Is there any documentation on how to provide my own requests session?

**Comment by Archmonger** [comment]
I've gone ahead and confirmed my initial theory.

On the old version of `_requests`, a new `requests` object was being created for every single request. So one thread gets one requests object.

The new version uses a shared requests instance, which every single thread has to communicate through. This becomes a major bottleneck in multithreaded applications since each requests object can only have 10 concurrent connections by default.

#### OLD VERSION
```python
    def _request(self, method, path, params=None, payload=None):
        url = self._get_complete_url(path)
        params = self._get_params(params)

        # Creates a new requests session for every connection, great for multithreaded applications
        response = requests.request(
            method, url, params=params,
            data=json.dumps(payload) if payload else payload,
            headers=self.headers)

        response.raise_for_status()
        response.encoding = 'utf-8'
        return response.json()
 ``` 

#### New version
```python        
    def _request(self, method, path, params=None, payload=None):
        url = self._get_complete_url(path)
        params = self._get_params(params)

        # This line can be problematic since it's using the same connection pool for every thread
        response = self.session.request(
            method, url, params=params,
            data=json.dumps(payload) if payload else payload,
            headers=self.headers)

        response.raise_for_status()
        response.encoding = 'utf-8'
        return response.json()
```

**Comment by p0psicles** [comment]
6. Provide your own request session object. And configure your desired connection pool size? 

Then no changes required?

**Comment by Archmonger** [comment]
Your number 6 is my **number 4** option. As of right now, your session pool configuration logic is an undocumented change that developers have no way of knowing about unless they ask, or manually inspect the source code.

**Comment by Archmonger** [comment]
I just thought of another option...
6. Instead of allowing the user to pass in a requests object, allow them to pass in requests session configuration parameters. A new sessions object would be created every call of `def _request(x)` and these configuration parameters (as **kwargs) will be applied every time. 

Would that help in your use case where you needed to pass in a specific requests object?

**Comment by p0psicles** [comment]
I'm using the session to configure a proxy. So in user space I create the session object and optionally hook the proxy configuration to it. Then I pass the session object. 

I don't think your solution would align well in my app. I think 1. Would be the best concession for both of us.

**Comment by Archmonger** [comment]
Glad we could reach a consensus 👍. I'll develop that tomorrow and open a PR.

**Comment by Archmonger** [comment]
PR has been made. 

Implements option 1, and within readme.md I've documented your REQUESTS_SESSION change made in v2.7.0

**Comment by celiao** [comment]
@Archmonger @p0psicles Thanks for your discussion and examination of options!  I agree option 1. is the best and most flexible for all users.  Option 1. also keeps `tmdbsimple` simple, which is a guiding principle of the design.

I will look over the PR, give it a test, and merge, if ready to go.

**Comment by Archmonger** [comment]
@celiao Can you update the revision to 2.7.1 for the sake of pypi?

Thanks!

**Comment by celiao** [comment]
Ah yes.  I updated the version to 2.8.0.  2.7 always bugged me because it looked like a Python version.  ;)
