### ISSUE TITLE
Movies, People, Tv

### ISSUE THREAD

**Issue by giuliaguglielmi** [celiao/tmdbsimple#80]
Hi! I have to do a university exam project. I should create a graph that has the actors as nodes, and as a link if they made a film in common. I was wondering if there were any functions to take a list of all the movies, TV series and actors. Thank you!

**Comment by p0psicles** [comment]
Maybe this is a good start. https://www.themoviedb.org/talk/5abb7747c3a368435c01156d

**Comment by giuliaguglielmi** [comment]
Thank you so much!!!

**Comment by Archmonger** [comment]
This PR is a question, not a bug report. Can be closed @celiao

**Comment by celiao** [comment]
Thanks, @Archmonger!
