### ISSUE TITLE
List of genres

### ISSUE THREAD

**Issue by AtomicNess123** [celiao/tmdbsimple#82]
I can't seem to find how to list all genres with their ID.
`tmdb.Genres.movie_list(language='en') `is supposed to do the job, but it won't.

**Comment by Archmonger** [comment]
This question does not contain enough information.

What do you receive when calling `tmdb.Genres.movie_list(language='en')`?

Additonally, this PR is a question, not a bug report. Can be closed @celiao

**Comment by AtomicNess123** [comment]
I get this:

```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-12-bb1c8af383f1> in <module>
----> 1 tmdb.Genres.movie_list(language='en')

TypeError: movie_list() missing 1 required positional argument: 'self'
```

**Comment by Archmonger** [comment]
@AtomicNess123 Genres is a class, and thus needs to be initialized.

The correct way of typing this would be `tmdb.Genres().movie_list(language='en')`

**Comment by AtomicNess123** [comment]
Now it works. Im a newbie in Python. I just wrote what you told me to above, and there were no brackets.
Now with the brackets, it works.

**Comment by celiao** [comment]
Thanks for your help, @Archmonger!
