### ISSUE TITLE
Connection Error while calling Function

### ISSUE THREAD

**Issue by theyashl** [celiao/tmdbsimple#83]
Code: `tmdbsimple.TV().airing_today()`

Expected Behavior: Method should return a list of TV objects

Observed Behavior: Connection to server getting aborted because of Connection Error.

Possible Problem: The code is trying to reuse the connection but the server is closing it because it has been idle for too long.

**Comment by celiao** [comment]
This code works fine:

# TV Airing Today Example

```python
import tmdbsimple as tmdb
tmdb.API_KEY = '<your api key>'
```

```python
results = tmdb.TV().airing_today();
results
```

Please compare it to what you are using.
