### ISSUE TITLE
Movies credits incorrect request

### ISSUE THREAD

**Issue by busterbeam** [celiao/tmdbsimple#84]
The request the library makes is `https://api.themoviedb.org/3/movie/0/credits?id=13448&api_key={obfucated_api_key}`
when the library should make the request `https://api.themoviedb.org/3/movie/13448/credits&api_key={obfucated_api_key}`

I think... by reading [this](https://developers.themoviedb.org/3/movies/get-movie-credits) link.  Please check this

**Comment by celiao** [comment]
The `movie_id` is located before `credits`, like your second URL, in [movies.py](https://github.com/celiao/tmdbsimple/blob/master/tmdbsimple/movies.py):
```
        'credits': '/{id}/credits',
```

Also, in the unit tests, the call to `test_movies_credits` passes.

Can you show me with a snippet of python code that a call to `tmdbsimple.Movie(id).credits()` isn't working?

**Comment by celiao** [comment]
Feel free to reopen this issue, if you are still experiencing problems after reviewing the above.
