### ISSUE TITLE
Specify a language for returned data

### ISSUE THREAD

**Issue by mysterfr** [celiao/tmdbsimple#9]
Hello,

Would it be possible to add some form of parameter allowing to pick a different language ?
For instance, I'd like to fetch the movie overview in French rather than English.

To do so, with PHP/cURL I simple add "&language=fr" to the queried URL.

For instance :

`http://api.themoviedb.org/3/movie/603?api_key=API_KEY&language=fr`
or
`http://api.themoviedb.org/3/search/movie?api_key=API_KEY&language=fr&query=matrix`

**Comment by celiao** [comment]
It probably wouldn't be too difficult.  Would you like to submit a pull request?
