### ISSUE TITLE
Support for contributions to TMDB?

### ISSUE THREAD

**Issue by henrydatei** [celiao/tmdbsimple#95]
Is there support for contributions to TMDB? I mean for example adding actors to a movie etc. Or do you know a Python package that allows me to do that?

**Comment by celiao** [comment]
You absolutely can contribute to The Movie Database (TMDB).

See the TMDB website for more information:

https://www.themoviedb.org/ (notice the bottom right bullet about contributing to the database)

![image](https://user-images.githubusercontent.com/5824630/224463619-c8b92031-e5d9-482a-9542-86a0807068db.png)

Go ahead, create an account, and poke around.
